export const results = [
  {
    "id": 54408,
    "slug": "35m-motor-yacht-shooting-star-sold",
    "size": "small",
    "category": null,
    "title": "Sold: 35m Pershing Shooting Star",
    "text": "The 35.37-metre Pershing motor yacht, Shooting Star has been sold with a last known asking price of €2,100,000.",
    "dateTime": "2022-01-11T16:00:00.000+01:00",
    "imageLink": "https://photos.superyachtapi.com/download/215539/large",
    "cardLink": "https://www.superyachttimes.com/yacht-news/35m-motor-yacht-shooting-star-sold",
    "categoryLink": "https://www.superyachttimes.com/news?filter=null"
  },
  {
    "id": 52041,
    "slug": "yacht-shooting-star-delta-sold",
    "size": "small",
    "category": null,
    "title": "30m Cantieri di Pisa yacht Shooting Star Delta sold in Athens",
    "text": "Yacht Shooting Star Delta has been sold after 685 days on the market for a last known asking price of €2,300,000. Find out more about the deal on SYT.",
    "dateTime": "2020-11-17T11:00:00.000+01:00",
    "imageLink": "https://photos.superyachtapi.com/download/102714/large",
    "cardLink": "https://www.superyachttimes.com/yacht-news/yacht-shooting-star-delta-sold",
    "categoryLink": "https://www.superyachttimes.com/news?filter=null"
  },
  {
    "id": 49711,
    "slug": "princess-yachts-management-interview",
    "size": "small",
    "category": "Business",
    "title": "Shooting with the Sheriff: 10 Questions with the Executive Chairman of Princess Yachts ",
    "text": "SYT sits down with Princess Yachts Executive Chairman, Antony Sheriff to learn how Princess is preparing for the future. ",
    "dateTime": "2019-03-21T17:00:00.000+01:00",
    "imageLink": "https://photos.superyachtapi.com/download/61372/large",
    "cardLink": "https://www.superyachttimes.com/yacht-news/princess-yachts-management-interview",
    "categoryLink": "https://www.superyachttimes.com/news?filter=Business"
  },
  {
    "id": 41872,
    "slug": "espen-oino-designed-shooting-star-sold",
    "size": "small",
    "category": null,
    "title": "​Espen Øino designed Shooting Star sold",
    "text": null,
    "dateTime": "2014-02-17T23:00:00.000+01:00",
    "imageLink": "https://photos.superyachtapi.com/download/135668/large",
    "cardLink": "https://www.superyachttimes.com/yacht-news/espen-oino-designed-shooting-star-sold",
    "categoryLink": "https://www.superyachttimes.com/news?filter=null"
  },
  {
    "id": 36876,
    "slug": "superyacht-shooting-star-to-star-at-the-monaco-yacht-show",
    "size": "small",
    "category": "Event News",
    "title": "Superyacht Shooting Star to star at the Monaco Yacht Show",
    "text": null,
    "dateTime": "2011-07-21T00:00:00.000+02:00",
    "imageLink": "https://photos.superyachtapi.com/download/135668/large",
    "cardLink": "https://www.superyachttimes.com/yacht-news/superyacht-shooting-star-to-star-at-the-monaco-yacht-show",
    "categoryLink": "https://www.superyachttimes.com/news?filter=Event%20News"
  },
  {
    "id": 36728,
    "slug": "superyacht-of-the-week-the-38-metre-shooting-star",
    "size": "small",
    "category": "Onboard",
    "title": "Superyacht of the Week: the 38 metre Shooting Star",
    "text": null,
    "dateTime": "2011-07-02T00:00:00.000+02:00",
    "imageLink": "https://photos.superyachtapi.com/download/135669/large",
    "cardLink": "https://www.superyachttimes.com/yacht-news/superyacht-of-the-week-the-38-metre-shooting-star",
    "categoryLink": "https://www.superyachttimes.com/news?filter=Onboard"
  },
  {
    "id": 36484,
    "slug": "superyacht-shooting-star-in-monaco",
    "size": "small",
    "category": "Photo of the Day",
    "title": "Superyacht Shooting Star in Monaco",
    "text": null,
    "dateTime": "2011-05-27T00:00:00.000+02:00",
    "imageLink": "https://photos.superyachtapi.com/download/135201/large",
    "cardLink": "https://www.superyachttimes.com/yacht-news/superyacht-shooting-star-in-monaco",
    "categoryLink": "https://www.superyachttimes.com/news?filter=Photo%20of%20the%20Day"
  }, {
    "id": 36403,
    "slug": "superyacht-shooting-star-for-sale-with-yco",
    "size": "small",
    "category": null,
    "title": "Superyacht Shooting Star for sale with YCO",
    "text": null,
    "dateTime": "2011-05-16T00:00:00.000+02:00",
    "imageLink": "https://photos.superyachtapi.com/download/134524/large",
    "cardLink": "https://www.superyachttimes.com/yacht-news/superyacht-shooting-star-for-sale-with-yco",
    "categoryLink": "https://www.superyachttimes.com/news?filter=null"
  },
  {
    "id": 36137,
    "slug": "danish-yachts-launches-superyacht-shooting-star",
    "size": "small",
    "category": "Build Updates",
    "title": "Danish Yachts launches superyacht Shooting Star",
    "text": null,
    "dateTime": "2011-03-29T00:00:00.000+02:00",
    "imageLink": "https://photos.superyachtapi.com/download/134524/large",
    "cardLink": "https://www.superyachttimes.com/yacht-news/danish-yachts-launches-superyacht-shooting-star",
    "categoryLink": "https://www.superyachttimes.com/news?filter=Build%20Updates"
  },
  {
    "id": 33789,
    "slug": "lift-emotion-bv-unveils-the-lifebuoy-shooting-unit-lsu01",
    "size": "small",
    "category": "Business",
    "title": "Lift Emotion BV unveils the lifebuoy shooting unit LSU01",
    "text": null,
    "dateTime": "2009-10-25T23:00:00.000+01:00",
    "imageLink": "https://photos.superyachtapi.com/download/129314/large",
    "cardLink": "https://www.superyachttimes.com/yacht-news/lift-emotion-bv-unveils-the-lifebuoy-shooting-unit-lsu01",
    "categoryLink": "https://www.superyachttimes.com/news?filter=Business"
  },
  {
    "id": 32194,
    "slug": "zdf-shooting-aboard-inspiration-and-nanou",
    "size": "small",
    "category": "Event News",
    "title": "ZDF-Shooting aboard Inspiration and Nanou",
    "text": null,
    "dateTime": "2008-08-12T00:00:00.000+02:00",
    "imageLink": "https://photos.superyachtapi.com/download/125252/large",
    "cardLink": "https://www.superyachttimes.com/yacht-news/zdf-shooting-aboard-inspiration-and-nanou",
    "categoryLink": "https://www.superyachttimes.com/news?filter=Event%20News"
  },
  {
    "id": "31671",
    "slug": "successful-tank-tests-for-38m-danish-yacht",
    "size": "small",
    "category": "Business",
    "title": "Successful tank tests for 38m Danish Yacht",
    "text": null,
    "dateTime": "2008-02-27T22:00:00.000Z",
    "imageLink": "https://photos.superyachtapi.com/download/124154/large",
    "cardLink": "https://www.superyachttimes.com/yacht-news/successful-tank-tests-for-38m-danish-yacht",
    "categoryLink": "https://www.superyachttimes.com/news?filter=Business"
  },
  {
    "id": "52476",
    "slug": "cantieri-di-pisa-acquisition",
    "size": "small",
    "category": "Business",
    "title": "Cantieri di Pisa receives new purchase offers",
    "text": "The Cantieri di Pisa acquisition case is reported to have four new purchase offers in the wake of Mondomarine's 2018 collapse. ",
    "dateTime": "2021-02-26T11:45:00.000Z",
    "imageLink": "https://photos.superyachtapi.com/download/113485/large",
    "cardLink": "https://www.superyachttimes.com/yacht-news/cantieri-di-pisa-acquisition",
    "categoryLink": "https://www.superyachttimes.com/news?filter=Business"
  },
  {
    "id": "52565",
    "slug": "baglietto-yacht-thunderball-i-nice",
    "size": "small",
    "category": "Photo of the Day",
    "title": "Baglietto motor yacht Thunderball I in Nice",
    "text": "The 33.5-metre Balietto yacht Thunderball I from 2001 spotted in the port of Nice on the Côte d'Azur.",
    "dateTime": "2021-03-18T07:00:00.000Z",
    "imageLink": "https://photos.superyachtapi.com/download/190287/large",
    "cardLink": "https://www.superyachttimes.com/yacht-news/baglietto-yacht-thunderball-i-nice",
    "categoryLink": "https://www.superyachttimes.com/news?filter=Photo%20of%20the%20Day"
  },
  {
    "id": "40092",
    "slug": "video-of-the-stunning-pershing-115-mistral-55",
    "size": "small",
    "category": "Fleet Updates",
    "title": "Video of the stunning Pershing 115 Mistral 55",
    "text": null,
    "dateTime": "2013-02-03T22:00:00.000Z",
    "imageLink": "https://photos.superyachtapi.com/download/137081/large",
    "cardLink": "https://www.superyachttimes.com/yacht-news/video-of-the-stunning-pershing-115-mistral-55",
    "categoryLink": "https://www.superyachttimes.com/news?filter=Fleet%20Updates"
  },
  {
    "id": "40174",
    "slug": "on-board-the-powerful-superyacht-mistral-55",
    "size": "small",
    "category": "Fleet Updates",
    "title": "On board the powerful superyacht Mistral 55",
    "text": null,
    "dateTime": "2013-02-19T22:00:00.000Z",
    "imageLink": "https://photos.superyachtapi.com/download/137081/large",
    "cardLink": "https://www.superyachttimes.com/yacht-news/on-board-the-powerful-superyacht-mistral-55",
    "categoryLink": "https://www.superyachttimes.com/news?filter=Fleet%20Updates"
  },
  {
    "id": "37688",
    "slug": "superyachts-mistral-55-perla-nero-and-negara-for-sale-with-cni",
    "size": "small",
    "category": null,
    "title": "Superyachts Mistral 55, Perla Nero and Negara for sale with CNI",
    "text": null,
    "dateTime": "2011-12-05T22:00:00.000Z",
    "imageLink": "https://photos.superyachtapi.com/download/137081/large",
    "cardLink": "https://www.superyachttimes.com/yacht-news/superyachts-mistral-55-perla-nero-and-negara-for-sale-with-cni",
    "categoryLink": "https://www.superyachttimes.com/news?filter=null"
  },
];
